###
GET http://localhost:8080/calificacion/
###
POST http://localhost:8080/calificacion
Content-Type: application/json
Accept: application/json

{
  "id_usuario": 1,
  "id_consulta": 3,
  "calificacion": 5,
  "fecha":"2002-02-01"

}