###
GET http://localhost:8080/mascota
###
POST http://localhost:8080/mascota
Content-Type: application/json
Accept: application/json

{
  "id_especie": 1,
  "id_raza": 1,
  "id_imagen": 1,
  "id_dueño": "1",
  "nombre_mascota": "Peluchin",
  "tamaño": "Mediano",
  "color": "Blanco",
  "sexo": "Macho",
  "fecha_registro": "2020-4-1"
}