###
POST http://localhost:8080/veterinario
Content-Type: application/json
Accept: application/json

{
  "id_usuario": 1,
  "id_veterinaria": 1,
  "id_imagen": 4,
  "nombre": "martin",
  "apellido": "Sanchez",
  "email": "martin@gmail.com",
  "departamento": "La Paz",
  "lugar_formacion": "loyola"
}
###
GET http://localhost:8080/veterinario/
